### PR TITLE
Create code of conduct

### LINKED ISSUE #61: Missing code of conduct
Quoting from [Github](https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/):

> A code of conduct defines standards for how to engage in a community.

See [giphy-js-sdk-core's](https://github.com/Giphy/giphy-js-sdk-core/blob/5df6da7af08d3941a7ae2d33de52bc45a8a6027f/CODE_OF_CONDUCT.md), [Facebook's](https://github.com/facebook/react-native/blob/e9e20e6c8335f27af8469cd23cb7ba079b0422f9/CODE_OF_CONDUCT.md) and [Microsoft's](https://opensource.microsoft.com/codeofconduct/) code of conduct.

### PR DESCRIPTION
**Pull request by rodrigobdz**
Import from [giphy-js-sdk-core](https://github.com/Giphy/giphy-js-sdk-core/pull/32). Fixes #61.

### CODE REVIEW

**Comment by rodrigobdz** [comment]
@dustfire Could you take a look at this PR? It would be helpful to have a code of conduct in the project.

**Comment by bejayoharen** [comment]
Closing this ancient unmerged pr.

**Comment by rodrigobdz** [comment]
> the best option is to **politely explain** to users that, although you value their contribution, you are unwilling to accept it and close their pull request.
[GitHub - Kindly Closing Pull Requests](https://github.com/blog/2124-kindly-closing-pull-requests)

@bejayoharen Could you explain why you are closing this unmerged PR?

**Comment by bejayoharen** [comment]
@rodrigobdz: as a matter of internal policy, we are closing all unmerged PRs that have been stale for more than 1 month. Feel free to reopen or tag someone on the team who can. I am unable to review this PR.

**Comment by rodrigobdz** [comment]
> @dustfire Could you take a look at this PR? It would be helpful to have a code of conduct in the project.

@bejayoharen I did tag someone from the team in a previous comment but got no answer.

**Comment by bejayoharen** [comment]
@giorgia This PR from @rodrigobdz has gone stale. Can you reopen if it's still relevant?

**Pull request closed without merging**
